### ISSUE TITLE
Some emojis are not rendered in help command

### ISSUE THREAD

**Issue by Thatkookooguy** [Androz2091/AtlantaBot#341]
## To Reproduce
Run the bot locally on any machine (windows, linux, docker, etc.)
Add it to a server
run `*help`

## Expected behavior
Should show the exact same help embed that the hosted Atlanta bot shows

### Result when running locally
![image](https://user-images.githubusercontent.com/10427304/98121697-4e376100-1eb8-11eb-8fc7-d24687b311d2.png)
### embed
![image](https://user-images.githubusercontent.com/10427304/98121658-4081db80-1eb8-11eb-9f87-22a3666c8906.png)

## Further details:
- atlanta version: `4.8.0`
- discord.js version: `^12.2.0`
- Node.js version: `node:12`
- Operating system: `linux`

## Additional context
I guess an additional step that I should do in **Discord** is missing from the Getting Started guide (I don't mind contributing and adding it myself). Maybe adding the emojis somewhere (guild?). not sure.

Can you please let me know what I should do do either create my own discord emojis for the bot or use the original atlanta-bot icons?

The same problem happens with the 'processing icon':
![show-bug](https://user-images.githubusercontent.com/10427304/98122854-d0745500-1eb9-11eb-861c-6622d70f97fe.gif)

**Comment by booleans-oss** [comment]
You need to add the emojis by yourself: However, it means that you need to change every id in the [custom emojis file](https://github.com/Androz2091/AtlantaBot/blob/master/emojis.json) in order to have emojis that actually work. (you can find the emojis by using [Discord's CDN](https://discord.com/developers/docs/reference#image-formatting-image-base-url) and going to the url `https://cdn.discordapp.com/emojis/{emoji_id}.png`.

I worked on this issue, in order to have a self-update custom emojis system but the main problem was that there are more than 50 emojis in that file. Therefore, you would have to upload the custom emojis locally in different servers if you want every one of them to be up and running correctly.

**Comment by Androz2091** [comment]
@booleans-oss @Thatkookooguy you can use https://www.atlanta-bot.fr/emojis

**Comment by Androz2091** [comment]
Some emojis are indeed missing in the help command. They will be added.

**Comment by Androz2091** [comment]
They have been added 👍
