### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by mythiccalss** [Androz2091/AtlantaBot#417]
**Please describe the problem you are having in as much detail as possible:**
Hi, when I start the bot it no longer appears online on discord and doesn't respond to any commands, though the console of the bot doesn't seem to show any errors: https://pastebin.com/dUfQUgaU
**To Reproduce**
Run bot
**Expected behavior**
A clear and concise description of what you expected to happen:
Bot should appear online and respond to commands
**Screenshots**
If applicable, add screenshots to help explain your problem:

**Further details:**
- atlanta version : 4.9.2
- discord.js version : 12.5.1
- Node.js version : 14.16.0
- Operating system : Windows

**Additional context**
Add any other context about the problem here:
/

**Comment by Androz2091** [comment]
This is pretty weird. Can you connect using another token?

**Comment by 11TStudio** [comment]
@Androz2091 After having similer issue I did re-search and debug the issue and found that the issue happens when the bot can't login.

This means;
1. The application/token got banned by Discord.
2. The applicaiton/token got rate limited because of the 1000 authentication limits / DAY

**In most cases ,as in my case and probably in @mythiccalss 's case, it is option 2.**

**Details;**
Since discord's client.login() method is promise based you can test this by putting await on front of it and you will see that the code is not moving further than the line where it tries to login, this already is enough to hint that something is wrong with the TOKEN and not the code.

**Debug;**
To be 100% sure we need to enable DiscordJS's Debug and modify the `client.login()` function. 
So this is what we need here;
```js
  client.on("debug", console.log);
  client.login(client.config.token).then(connection => {
  connection.on("debug", console.log);
  });
```
The response looks like;
![image](https://user-images.githubusercontent.com/25463237/115565897-14b5af00-a2ba-11eb-9fd1-4c65ebceb12e.png)
As you see I have 0 as remaining amount :)

**Note;**
- Chaning/Regenerate token
   - **WILL NOT WORK**
- Making new bot and using that token;
   - **WILL WORK**  
- Waiting the time it states in the debug message;
  - **WILL WORK**

**Solution**
Well there is not really a solution since this is a user based error/issue. You should not do whatever you are doing with the bot.
In my case it was PM2 auto restarting the bot. (The bot was trying to open a dashboard at port 80 which was already used by apache2 service... I did close it but however forget to remove it from auto start 🦀 )  

**About catching this**
You can't catch this. `client.on('rateLimit', ...` is not catching this since this is a daily identify limit... (as in DiscordJS v12.5.3)

**Comment by Androz2091** [comment]
All right thank you for all these details 👍 
I hope that they'll be useful for someone else
