### ISSUE TITLE
"сonfig.apiKeys.blagueXYZ" problem.

### ISSUE THREAD

**Issue by SadnessOfficial** [Androz2091/AtlantaBot#597]
Hello, I have a problem, maybe someone else has the same problem.

What to do if the site has closed the server database = "blague.xyz", I understand that they have what in the documentation what on the site describes why the api function is removed:
"The token system is currently disabled. So you can use the API without a token! / The token system is currently disabled. So you can use the api without a token!"

If anyone has any idea what to do. And another request, if you do not know the answer, do not write, remove this API and everything associated with it.
Thanks in advance who knows the answer!

**Comment by SickProdigy** [comment]
Well your question kind of answers itself. It says you "can" use it without, which I assume means you can still use it also. Doesn't say it will error if you use the api with token does it?

And I assume that because I'm running a bit older version and api is working fine for blaguexyz

But if it's currently disabled and labeled like that, it may mean they might enable it again sometime in the future.
